# config.py - Generated by setup.py
import MetaTrader5 as mt5


# -- إعدادات الاتصال والرمز
SYMBOL = "XAUUSDm"
TIMEFRAME = mt5.TIMEFRAME_M5
TIMEFRAME_HIGHER = mt5.TIMEFRAME_M15 # إطار زمني أعلى لتحليل إضافي
N_BARS_FETCH = 10000 # عدد الشموع لجلبها من السيرفر

# -- إعدادات MT5
MT5_LOGIN = 261009880
MT5_PASS = "Amine2002@"
MT5_SERVER = "Exness-MT5Trial16"
TELEGRAM_TOKEN = "AAFtwaP6aHMJg9ttJNiUwPG-Of0QZ7NxiiQ"
TELEGRAM_CHAT_ID = "8423946950"
LOT_RISK_PER_TRADE = 0.1

# -- إعدادات النموذج والتدريب
SEQ_LEN = 48             # طول التسلسل (ذاكرة النموذج)
TEST_SPLIT = 0.2         # نسبة بيانات الاختبار
VAL_SPLIT = 0.15         # نسبة بيانات التحقق (من بيانات التدريب)
EPOCHS = 30              # عدد دورات التدريب
BATCH_SIZE = 64          # حجم الدفعة

# -- إعدادات هندسة الميزات والأهداف
LABEL_HORIZON = 5        # عدد الشموع المستقبلية للتنبؤ
UP_THRESHOLD_REL = 0.0007  # عتبة الصعود لتحديد إشارة "شراء"
DOWN_THRESHOLD_REL = -0.0007 # عتبة الهبوط لتحديد إشارة "بيع"

# -- إعدادات البحث عن أفضل Hyperparameters (Optuna)
OPTUNA_TRIALS = 30       # عدد محاولات البحث (كلما زاد كان أفضل ولكن أبطأ)
TUNE_HYPERPARAMS = True  # غيرها إلى False لتخطي البحث واستخدام نموذج افتراضي

# -- إعدادات التداول الحي
RUN_LIVE = True          # غيرها إلى True لبدء التداول الحي
LOT_RISK_PER_TRADE = 0.01 # المخاطرة لكل صفقة (1% من رصيد الحساب)
ATR_SL_MULTIPLIER = 1.5   # مضاعف ATR لوقف الخسارة
ATR_TP_MULTIPLIER = 3.0   # مضاعف ATR لجني الأرباح
SLEEP_SECONDS = 300       # 300 ثانية للإطار الزمني M5

# -- إعدادات التكاليف (عدّل حسب وسيطك)
SPREAD_PIPS = 20.0        # السبريد بالنقاط (مثال للذهب)
SLIPPAGE_PIPS = 5.0       # الانزلاق السعري بالنقاط
COMMISSION_PER_LOT = 7.0  # العمولة لكل لوت (بالدولار)

# -- أسماء الملفات المحفوظة
MODEL_FILE = "lstm_xauusd_model_v2.h5"
SCALER_FILE = "scaler_v2.save"
BACKTEST_FILE = "backtest_results_v2.xlsx"
TRADES_LOG_FILE = "live_trades_log_v2.csv"
# -- User Defined Settings --


