# setup.py
import os

def run_setup():
    print("--- AI Trading Bot Interactive Setup ---")
    print("Please provide the following details to generate your config.py file.\n")

    config = {}

    # MT5 Credentials
    print("-- MetaTrader 5 Account --")
    config['MT5_LOGIN'] = input("Enter your MT5 Login ID: ")
    config['MT5_PASS'] = input("Enter your MT5 Password: ")
    config['MT5_SERVER'] = input("Enter your MT5 Server: ")

    # Telegram Notifications
    print("\n-- Telegram Notifications (Optional, press Enter to skip) --")
    print("You need to create a bot with @BotFather on Telegram.")
    config['TELEGRAM_TOKEN'] = input("Enter your Telegram Bot Token: ")
    config['TELEGRAM_CHAT_ID'] = input("Enter your Telegram Chat ID: ")

    # Trading Settings
    print("\n-- Trading Settings --")
    risk = input("Enter your risk per trade as a percentage (e.g., 1 for 1%): ")
    config['LOT_RISK_PER_TRADE'] = str(float(risk) / 100.0) if risk else "0.01"

    # Generate config.py
    if os.path.exists('config.py'):
        print("\nWarning: config.py already exists. It will be overwritten.")

    with open('config.py', 'w', encoding='utf-8') as f:
        f.write("# config.py - Generated by setup.py\n")
        f.write("import MetaTrader5 as mt5\n\n")

        # Write user-defined values
        f.write("# -- User Defined Settings --\n")
        f.write(f"MT5_LOGIN = {config['MT5_LOGIN']}\n" if config['MT5_LOGIN'].isdigit() else f"MT5_LOGIN = \"{config['MT5_LOGIN']}\"\n")
        f.write(f"MT5_PASS = \"{config['MT5_PASS']}\"\n")
        f.write(f"MT5_SERVER = \"{config['MT5_SERVER']}\"\n")
        f.write(f"TELEGRAM_TOKEN = \"{config['TELEGRAM_TOKEN']}\"\n")
        f.write(f"TELEGRAM_CHAT_ID = \"{config['TELEGRAM_CHAT_ID']}\"\n")
        f.write(f"LOT_RISK_PER_TRADE = {config['LOT_RISK_PER_TRADE']}\n")

        # Write default static values
        f.write("\n# -- Default System Settings --\n")
        f.write("SYMBOL = \"XAUUSD\"\n")
        f.write("TIMEFRAME = mt5.TIMEFRAME_M5\n")
        f.write("N_BARS_FETCH = 10000\n")
        f.write("SEQ_LEN = 48\n")
        f.write("EPOCHS = 30\n")
        f.write("BATCH_SIZE = 64\n")
        f.write("LABEL_HORIZON = 5\n")
        f.write("UP_THRESHOLD_REL = 0.0007\n")
        f.write("DOWN_THRESHOLD_REL = -0.0007\n")
        f.write("TUNE_HYPERPARAMS = True\n")
        f.write("OPTUNA_TRIALS = 30\n")
        f.write("RUN_LIVE = False\n")
        f.write("ATR_SL_MULTIPLIER = 1.5\n")
        f.write("ATR_TP_MULTIPLIER = 3.0\n")
        f.write("SLEEP_SECONDS = 300\n")
        f.write("MODEL_FILE = \"lstm_xauusd_model_v2.h5\"\n")
        f.write("SCALER_FILE = \"scaler_v2.save\"\n")
        f.write("BACKTEST_FILE = \"backtest_results_v2.xlsx\"\n")
        f.write("TRADES_LOG_FILE = \"live_trades_log_v2.csv\"\n")


    print("\n✅ Success! `config.py` has been created.")
    print("You can now run the main bot using `python main.py` or the dashboard using `streamlit run dashboard.py`.")

if __name__ == "__main__":
    run_setup()